language: android
dist: trusty

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-29.0.3
    - android-29
    - android-21
    - sys-img-armeabi-v7a-android-21

before_script:
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a --tag google_apis
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator

script:
  - ./gradlew connectedAndroidTest

before_install:
  - chmod +x gradlew

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache/