env:
  global:
    - CC_TEST_REPORTER_ID=2e68fe183d7869528ce403ed6117cc4d0a06a3177f2ed1e55a2f230d4a00ae3c

language: android
dist: trusty

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

android:
  components:
    - tools
    - build-tools-29.0.3
    - android-29

before_install:
  - chmod +x gradlew

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache/
